### ISSUE TITLE
Is there a way to open the link just by clicking it ?

### ISSUE THREAD

**Issue by anemdhana** [mlewand/ckeditor-plugin-openlink#2]
I have a requirement, instead of choosing to open from toolbar button or from right click context, can the link be opened by just clicking on it ?

**Comment by mlewand** [comment]
@anemdhana I'm sorry for late response. Yes it's possible to open it with the mouse. By default you can do that by holding CTRL/CMD and clicking at link. But unfortunately due to IE bugs it doesn't work on IE so this part is supported only on FF, Chrome and Safari (IE still supports context menu though).

If you need to adjust modifier keys you can use `config.openlink_modifier` key, e.g. `config.openlink_modifier = CKEDITOR.CTRL + CKEDITOR.SHIFT` will open window once clicked with shift, ctrl/cmd or both! See [README.md](https://github.com/mlewand/ckeditor-plugin-openlink/blob/master/README.md) for more details.
